const battleCards = [
  {
    id: "community_conflict",
    name: "社區衝突",
    cost: 1,
    type: "Attack",
    rarity: "普通",
    desc: "造成 8 點壓力傷害。",
    effect: { damage: 8 },
    shopCost: 2,
  },
  {
    id: "route_control",
    name: "動線整理",
    cost: 1,
    type: "Defense",
    rarity: "普通",
    desc: "覆蓋防禦牌，被攻擊時抵擋 12 點傷害。",
    effect: { block: 12 },
    shopCost: 2,
  },
  {
    id: "community_meeting",
    name: "社區會議",
    cost: 1,
    type: "Defense",
    rarity: "普通",
    desc: "居民先溝通，抵擋 10 點傷害並增加民心。",
    effect: { block: 10, publicSupport: 1 },
    shopCost: 3,
  },
  {
    id: "first_aid",
    name: "臨時修補",
    cost: 2,
    type: "Heal",
    rarity: "稀有",
    desc: "回復 12 點生命值。",
    effect: { heal: 12 },
    shopCost: 3,
  },
  {
    id: "poison_dart",
    name: "謠言壓力",
    cost: 2,
    type: "Debuff",
    rarity: "稀有",
    desc: "造成 6 點傷害，並讓對方下次更容易受傷。",
    effect: { damage: 6, poison: 1, vulnerable: 1 },
    shopCost: 3,
  },
  {
    id: "snare_trap",
    name: "預先分流",
    cost: 1,
    type: "Trap",
    rarity: "稀有",
    desc: "覆蓋陷阱。被攻擊時反制 6 點傷害。",
    effect: { trapDamage: 6 },
    shopCost: 3,
  },
  {
    id: "battle_focus",
    name: "行動聚焦",
    cost: 0,
    type: "Utility",
    rarity: "史詩",
    desc: "抽 1 張牌並回復 1 點能量。",
    effect: { draw: 1, energy: 1 },
    shopCost: 4,
  },
];

const communityMainCards = [
  {
    id: "main_hsinchu_food",
    name: "新竹米粉與貢丸",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/01_hsinchu_rice_noodles_meatballs.png",
    communityType: "食品特產社區",
    desc: "在地好味道能帶來收入，也需要讓故事被理解。",
    scores: { income: 2, tourism: 0, culture: 1, ecology: 0, publicSupport: 0 },
    weakAttacks: ["只賣貨", "低價競爭", "退燒", "說錯"],
    recommendedDeck: ["導覽", "故事地圖", "展售", "預算表"],
    fixedRisk: "連續兩回合只增加收入時，文化 -1。",
    shopCost: 5,
  },
  {
    id: "main_kaohsiung_squid",
    name: "高雄花枝丸觀光工廠",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/02_kaohsiung_squid_ball_factory.png",
    communityType: "水產加工社區",
    desc: "加工體驗能創造收入，也要兼顧安全與地方故事。",
    scores: { income: 2, tourism: 1, culture: 1, ecology: 0, publicSupport: 0 },
    weakAttacks: ["故障", "缺工", "只賣貨", "破財"],
    recommendedDeck: ["安檢表", "預算表", "導覽", "分類站"],
    fixedRisk: "體驗推廣時，支付人力 1 或技術 1。",
    shopCost: 5,
  },
  {
    id: "main_changhua_cookie",
    name: "彰化餅乾觀光工廠",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/03_changhua_cookie_factory.png",
    communityType: "產業體驗社區",
    desc: "體驗經濟很熱鬧，但要避免只剩打卡與消費。",
    scores: { income: 2, tourism: 2, culture: 0, ecology: 0, publicSupport: 0 },
    weakAttacks: ["只賣貨", "髒亂", "破財", "缺工"],
    recommendedDeck: ["分類站", "預算表", "導覽", "預約制"],
    fixedRisk: "收入暴增時，生態 -1 或錢 -1。",
    shopCost: 5,
  },
  {
    id: "main_nantou_tea",
    name: "南投茶葉與茶博活動",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/04_nantou_tea_expo.png",
    communityType: "農產節慶社區",
    desc: "茶文化可以結合觀光，但天候與活動成本要先想好。",
    scores: { income: 0, tourism: 2, culture: 2, ecology: 0, publicSupport: 0 },
    weakAttacks: ["颱風", "缺工", "假表演", "退燒"],
    recommendedDeck: ["雨備", "導覽", "志工名單", "預約制"],
    fixedRisk: "遇天氣事件時，收入 -2。",
    shopCost: 5,
  },
  {
    id: "main_yunlin_janfusun",
    name: "雲林劍湖山與農產推廣",
    cost: 3,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/05_yunlin_janfusun_farm_promo.png",
    communityType: "遊樂觀光社區",
    desc: "大型觀光帶來人潮，也要把人潮導回地方農產。",
    scores: { income: 2, tourism: 4, culture: 0, ecology: 0, publicSupport: 0 },
    weakAttacks: ["塞爆", "搶車位", "只賣貨", "門票太貴"],
    recommendedDeck: ["接駁", "動線", "展售", "分流圖"],
    fixedRisk: "交通壓力累積 3 時，民心 -2。",
    shopCost: 6,
  },
  {
    id: "main_pingtung_indigenous",
    name: "屏東原住民族文化園區",
    cost: 3,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/06_pingtung_indigenous_culture_park.png",
    communityType: "族群文化社區",
    desc: "文化展示要被看見，也要被尊重與正確理解。",
    scores: { income: 0, tourism: 1, culture: 4, ecology: 0, publicSupport: 0 },
    weakAttacks: ["說錯", "假表演", "只賣貨", "拍照干擾"],
    recommendedDeck: ["禮俗解說", "長輩審稿", "資料夾", "導覽"],
    fixedRisk: "文化誤用時，文化傷害 +1。",
    shopCost: 6,
  },
  {
    id: "main_chiayi_blue_shoe",
    name: "嘉義布袋藍色玻璃鞋",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/07_chiayi_budai_blue_glass_shoe.png",
    communityType: "地景藝術社區",
    desc: "打卡景點很吸睛，但不能讓社區只剩拍照。",
    scores: { income: 1, tourism: 3, culture: 0, ecology: 0, publicSupport: 0 },
    weakAttacks: ["爆量", "空拍照", "維修費", "髒亂"],
    recommendedDeck: ["動線", "分類站", "導覽", "預算表"],
    fixedRisk: "觀光暴增時，需支付維護費。",
    shopCost: 5,
  },
  {
    id: "main_hualien_bear",
    name: "花蓮玉里黑熊車站偶",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/08_hualien_yuli_black_bear_station.png",
    communityType: "生態打卡社區",
    desc: "生態意象能吸引人，也要避免被過度商品化。",
    scores: { income: 0, tourism: 2, culture: 0, ecology: 1, publicSupport: 0 },
    weakAttacks: ["玩壞", "空拍照", "過開發", "說錯"],
    recommendedDeck: ["導覽", "生態解說", "澄清稿", "資料夾"],
    fixedRisk: "只衝觀光時，下一回合民心 -1。",
    shopCost: 5,
  },
  {
    id: "main_tainan_milkfish",
    name: "台南虱目魚頭人",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/09_tainan_milkfish_head_mascot.png",
    communityType: "地方梗與水產社區",
    desc: "網路梗可以變成地方入口，但需要連回真實產業。",
    scores: { income: 2, tourism: 2, culture: 0, ecology: 0, publicSupport: 0 },
    weakAttacks: ["玩壞", "退燒", "只賣貨", "抗議"],
    recommendedDeck: ["導覽", "分類站", "澄清稿", "故事地圖"],
    fixedRisk: "公開宣傳時，抽文化或人潮攻擊。",
    shopCost: 5,
  },
  {
    id: "main_miaoli_wood",
    name: "苗栗三義木雕老街",
    cost: 2,
    type: "MainTheme",
    rarity: "主線",
    image: "../card_bank/main_cards/images/10_miaoli_sanyi_woodcarving_street.png",
    communityType: "工藝保存社區",
    desc: "工藝保存要投入時間與人力，才不會只剩商品。",
    scores: { income: 0, tourism: 0, culture: 3, ecology: 0, publicSupport: 0 },
    weakAttacks: ["缺工", "失傳", "只賣貨", "退燒"],
    recommendedDeck: ["長輩審稿", "導覽", "志工名單", "故事地圖"],
    fixedRisk: "未投入人力或時間時，文化 -1。",
    shopCost: 5,
  },
];

const bonusCards = [
  {
    id: "bonus_elder_help",
    name: "長輩幫忙",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/01_elder_help.png",
    desc: "瞬間：文化 +1、民心 +1。延時：下次文化錯誤類攻擊無效。",
    effect: { culture: 1, publicSupport: 1 },
    shopCost: 3,
  },
  {
    id: "bonus_temp_work_crew",
    name: "臨時工班",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/02_temp_work_crew.png",
    desc: "瞬間：技術 +2。延時：下次維修類攻擊少扣錢 2。",
    effect: { tech: 2 },
    shopCost: 3,
  },
  {
    id: "bonus_good_reputation",
    name: "好口碑",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/03_good_reputation.png",
    desc: "瞬間：民心 +1、幸運值 +1。延時：下次受到攻擊傷害 -1。",
    effect: { publicSupport: 1, luck: 1 },
    shopCost: 3,
  },
  {
    id: "bonus_social_share",
    name: "社群轉發",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/04_social_share.png",
    desc: "瞬間：觀光 +2、幸運值 +1。延時：本回合若沒增加文化，回合結束文化 -1。",
    effect: { tourism: 2, luck: 1 },
    shopCost: 4,
  },
  {
    id: "bonus_crowd_bonus",
    name: "人潮紅利",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/05_crowd_bonus.png",
    desc: "瞬間：觀光 +2、收入 +1。延時：觀光達 6 以上額外抽 1 張人潮攻擊。",
    effect: { tourism: 2, income: 1 },
    shopCost: 4,
  },
  {
    id: "bonus_local_spending",
    name: "在地消費",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/06_local_spending.png",
    desc: "瞬間：錢 +1、收入 +2。延時：接下來 2 回合，每回合收入 +1。",
    effect: { money: 1, income: 2 },
    shopCost: 4,
  },
  {
    id: "bonus_good_weather",
    name: "好天氣",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/07_good_weather.png",
    desc: "瞬間：幸運值 +1、觀光 +1。延時：下次增加觀光時，額外 +1。",
    effect: { luck: 1, tourism: 1 },
    shopCost: 3,
  },
  {
    id: "bonus_volunteers_arrive",
    name: "志工來了",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/08_volunteers_arrive.png",
    desc: "瞬間：人口 +1、人力 +2。延時：下次支付人力成本 -1。",
    effect: { population: 1, manpower: 2 },
    shopCost: 4,
  },
  {
    id: "bonus_small_luck",
    name: "小確幸",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/09_small_luck.png",
    desc: "瞬間：幸運值 +2。延時：下次不利事件可重抽 1 次。",
    effect: { luck: 2 },
    shopCost: 4,
  },
  {
    id: "bonus_grant_funding",
    name: "補助款",
    cost: 0,
    type: "Utility",
    rarity: "普通",
    image: "../card_bank/bonus_cards/images/10_grant_funding.png",
    desc: "瞬間：錢 +3。延時：無。",
    effect: { money: 3 },
    shopCost: 4,
  },
];

function readCardJsonBank() {
  return [...battleCards, ...communityMainCards, ...bonusCards];
}

const sampleCards = (typeof window !== "undefined" && Array.isArray(window.cardBankCards))
  ? window.cardBankCards
  : readCardJsonBank();

if (typeof module !== "undefined" && typeof module.exports !== "undefined") {
  module.exports = sampleCards;
} else {
  window.sampleCards = sampleCards;
  window.communityMainCards = communityMainCards;
  window.communityBonusCards = bonusCards;
}
